[access_switches]
sw-room1 ansible_host=172.20.10.11
sw-room2 ansible_host=172.20.10.12
sw-room3 ansible_host=172.20.10.13
sw-room4 ansible_host=172.20.10.14
sw-room5 ansible_host=172.20.10.15
sw-room6 ansible_host=172.20.10.16
sw-room7 ansible_host=172.20.10.17
sw-room8 ansible_host=172.20.10.18
sw-room9 ansible_host=172.20.10.19

[access_switches:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_user=admin
ansible_password=SecurePass123!
ansible_become=yes
ansible_become_method=enable
ansible_become_password=EnableSecret123!
